### ISSUE TITLE
Invalid Syntax, connection.py, Python 3

### ISSUE THREAD

**Issue by robinsonkwame** [deavid/bjsonrpc#15]
(py34)kwame@kwame-N4110:$ pip install -e git+https://github.com/deavid/bjsonrpc.git@master#egg=bjson
Obtaining bjson from git+https://github.com/deavid/bjsonrpc.git@master#egg=bjson
  Updating /home/kwame/py34/src/bjson clone (to master)
Installing collected packages: bjson
  Running setup.py develop for bjson
Successfully installed bjson

(py34)kwame@kwame-N4110:$ python

Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bjsonrpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kwame/py34/src/bjson/bjsonrpc/__init__.py", line 40, in <module>
    from bjsonrpc.main import createserver, connect
  File "/home/kwame/py34/src/bjson/bjsonrpc/main.py", line 14, in <module>
    import bjsonrpc.server
  File "/home/kwame/py34/src/bjson/bjsonrpc/server.py", line 36, in <module>
    from bjsonrpc.connection import Connection
  File "/home/kwame/py34/src/bjson/bjsonrpc/connection.py", line 758
    print self._wbuffer
             ^
SyntaxError: invalid syntax
>>>

**Comment by deavid** [comment]
Thanks for your submission.

I'm not using python3, so i didn't notice the issue.

I modified my master branch to work with python3. I hope this issue is fixed now.
